name: Production

on:
  push:
    branches:
      - main 

jobs:
  production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://mails.cybervilla.xyz

    steps:
      - name: Tempmails
        uses: actions/checkout@v3

      - name: Production
        run: echo "Deployed Locally"

      - name: Done!
        run: echo "Deployment completed"
